language: csharp
solution: Badminton.sln
install:
  - nuget restore Badminton.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug Badminton.sln
  - mono ./testrunner/NUnit.Runners.*/tools/nunit-console.exe "./Badminton UnitTest/bin/Debug/Badminton UnitTest.dll"

